# Generated by Django 4.1 on 2022-12-14 04:07

from django.db import migrations, models
import my_folio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_site', models.CharField(max_length=200)),
                ('user_comment', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='My_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_cat', models.CharField(default='', max_length=50)),
                ('project_clinet', models.CharField(max_length=50)),
                ('project_date', models.DateField()),
                ('project_url', models.URLField()),
                ('project_details', models.TextField(max_length=500)),
                ('project_img1', models.ImageField(blank=True, null=True, upload_to=my_folio.models.filepath)),
                ('project_img2', models.ImageField(blank=True, null=True, upload_to=my_folio.models.filepath)),
                ('project_img3', models.ImageField(blank=True, null=True, upload_to=my_folio.models.filepath)),
            ],
        ),
        migrations.CreateModel(
            name='User_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_subject', models.CharField(max_length=200)),
                ('user_message', models.TextField(max_length=500)),
            ],
        ),
    ]
