# Generated by Django 4.1 on 2022-12-15 09:24

from django.db import migrations, models
import django.db.models.deletion
import my_folio.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_folio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Postes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_name', models.CharField(max_length=100, null=True)),
                ('Blog_cat', models.CharField(default='', max_length=50, null=True)),
                ('Blog_date', models.DateField(null=True)),
                ('Blog_details', models.TextField(max_length=500, null=True)),
                ('Blog_img1', models.ImageField(blank=True, null=True, upload_to=my_folio.models.filepath)),
            ],
        ),
        migrations.AlterField(
            model_name='blog_comment',
            name='user_comment',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_comment',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog_comment',
            name='user_site',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog_comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_folio.blog_postes'),
        ),
    ]
