# Generated by Django 4.1 on 2022-12-15 10:24

from django.db import migrations, models
import my_folio.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_folio', '0002_blog_postes_alter_blog_comment_user_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_postes',
            name='Blog_shourtdetails',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='blog_postes',
            name='Blog_details',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='blog_postes',
            name='Blog_img1',
            field=models.ImageField(blank=True, null=True, upload_to=my_folio.models.filepath_posts),
        ),
    ]
