# Generated by Django 4.1 on 2022-12-16 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_folio', '0004_blog_postes_blog_conclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_comment',
            name='comment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_comment',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='blog_postes',
            name='Blog_conclusion',
            field=models.TextField(max_length=700, null=True),
        ),
    ]
